const DocumentActionTypes = {
	DOCUMENTS_ACTION_MESSAGE: 'DOCUMENTS_ACTION_MESSAGE',
	LOAD_DOCUMENTS_START: 'LOAD_DOCUMENTS_START',
	LOAD_DOCUMENTS_SUCCESS: 'LOAD_DOCUMENTS_SUCCESS',
	LOAD_DOCUMENTS_FAILURE: 'LOAD_DOCUMENTS_FAILURE',
	UPLOAD_DOCUMENT: 'UPLOAD_DOCUMENT'
}

export default DocumentActionTypes