const BannedWordsActionTypes = {
	ACTION_MESSAGE: 'ACTION_MESSAGE',
	LOAD_WORDS_START: 'LOAD_WORDS_START',
	LOAD_WORDS_SUCCESS: 'LOAD_WORDS_SUCCESS',
	LOAD_WORDS_FAILURE: 'LOAD_WORDS_FAILURE',
	CREATE_WORD: 'CREATE_WORD',
	DELETE_WORD: 'DELETE_WORD'
}

export default BannedWordsActionTypes